language: php

php:
    - 5.5
    - 5.4
    - 5.3

# Install lib-memcached
install:
    - sudo apt-get install -qq libmemcached-dev

# Add Memcached service
services:
    - memcache

# Hooks
before_script:
    - travis/before.sh

# Notifications
notifications:
    email:
        - ci@angrybytes.com
